name = "Glass House"
author = "BuckFiddy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "237ca29ced0ed3421946b7396239e358e79620b7c5fcef4e8ecc0e80908780ac"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
